name: CD (Publish to AUR)

on:
  push:
    tags:
      - 'v*'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install pacman dependencies
        run: |
          pacman -Sy --noconfirm --needed base-devel git rust openssh sudo
          
          # Buat user non-root 'builder'
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Fix Workspace Permissions
        run: |
          # Berikan kepemilikan direktori workspace ke user builder agar tidak permission denied
          chown -R builder:builder /__w/Atha

      - name: Setup SSH for AUR
        shell: su - builder -c "bash {0}"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur_id_rsa
          chmod 600 ~/.ssh/aur_id_rsa
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          
          git config --global user.name "Bangkah"
          git config --global user.email "bangkah@aur.archlinux.org"
          git config --global --add safe.directory '*'
          
          cat << EOF > ~/.ssh/config
          Host aur.archlinux.org
            IdentityFile ~/.ssh/aur_id_rsa
            User aur
          EOF
      - name: Generate .SRCINFO & Sync to AUR
        env:
          TAG_REF: ${{ github.ref_name }}
        run: |
          VERSION="${TAG_REF#v}"
          
          echo "Building for version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Error: Version is empty!"
            exit 1
          fi
          
          sudo -u builder bash -c "
            cd /__w/Atha/Atha
            sed -i 's/^pkgver=.*/pkgver=$VERSION/' PKGBUILD
            sed -i 's/^pkgrel=.*/pkgrel=1/' PKGBUILD
            
            makepkg --printsrcinfo > .SRCINFO
            
            git clone ssh://aur@aur.archlinux.org/atha.git /tmp/aur-atha
            cp PKGBUILD /tmp/aur-atha/
            cp .SRCINFO /tmp/aur-atha/
            
            cd /tmp/aur-atha
            git add PKGBUILD .SRCINFO
            git commit -m 'maint: release version $VERSION' || echo 'No changes to commit'
            git push origin master
          "
     